ttsx/ttsx/urls.py
#coding=utf-8
"""ttsx URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # 用于后台站点管理
    url(r'^admin/', include(admin.site.urls)),
    # 用户应用
    url(r'^user/', include('ttsx_user.urls')),
    # 商品应用
    url('^',include('ttsx_goods.urls')),
    # 富文本编辑器路径
    url(r'^tinymce/', include('tinymce.urls')),
    # 全文检索路径,当自定义搜索的时候这条就不用了
    # url(r'^search/', include('haystack.urls')),
    # 购物车应用
    url('^cart/',include('ttsx_cart.urls')),
    # 用于全部订单提交
    url(r'^order/',include('ttsx_order.urls')),
]

ttsx/ttsx_user/urls.py
from django.conf.urls import url
import views
urlpatterns = [
    url(r'^register/$',views.register),
    url(r'^register_handle/$',views.register_handle),
    url(r'^register_estimate/$',views.register_estimate),
    url(r'^login/$', views.login),
    url(r'^login_handle/$', views.login_handle),
    url(r'^logout/$',views.logout),
    url(r'^center/$',views.center),
    url(r'^order/$',views.order),
    url(r'^site/$',views.site),
    url(r'^islogin/$',views.islogin),
]

ttsx/ttsx_order/models.py
#coding=utf-8
from django.db import models
from ttsx_user.models import UserInfo
from ttsx_goods.models import GoodsInfo
# Create your models here.


# 主订单 当有字段一开始未传内容时要设定默认值
class OrderMain(models.Model):
    # 表示id primary_key：若为True，则该字段会成为模型的主键字段,需自己手动添加
    order_id = models.CharField(max_length=20,primary_key=True)#年/月/日/uid
    # 用户表和用户是一对多关系,ForeignKey：一对多，将字段定义在多的一端中
    user = models.ForeignKey(UserInfo)
    # 下单日期,参数auto_now_add表示当对象第一次被创建时自动设置当前时间，用于创建的时间戳，它总是使用当前日期
    order_date = models.DateTimeField(auto_now_add=True)
    # 表示总支付金额,DecimalField十进制浮点数
    # max_digits表示总位数,decimal_places表示小数位数
    total = models.DecimalField(max_digits=8,decimal_places=2,default=0)
    # 订单状态，已支付还是未支付
    state = models.IntegerField(default=0)


# 详细订单
class OrderDetail(models.Model):
    order = models.ForeignKey(OrderMain)
    goods = models.ForeignKey(GoodsInfo)
    count = models.IntegerField()
    price = models.DecimalField(max_digits=5,decimal_places=2)

ttsx/ttsx_user/models.py
#coding=utf-8
from django.db import models
from hashlib import sha1

# Create your models here.


class UserInfo(models.Model):
    uname = models.CharField(max_length=20)  #用户名
    upwd = models.CharField(max_length=40)  #用户密码
    umail = models.CharField(max_length=20) #邮件
    uphone = models.CharField(default='',max_length=11)  #电话
    uaddress = models.CharField(default='',max_length=100)  #收件地址
    ushou = models.CharField(default='',max_length=20)   #收件人
    ucode = models.CharField(default='',max_length=10)   #邮编
    # def __str__(self):
    #     return self.uname

ttsx/ttsx_user/views.py
#coding=utf-8
from django.shortcuts import render,redirect
from models import *
from hashlib import sha1
from django.http import JsonResponse
import datetime
from ttsx_goods.models import GoodsInfo
from ttsx_order.models import OrderMain
from django.core.paginator import Paginator

# Create your views here.


#跳转到注册页面
def register(request):
    context = {'title':'注册','top':'0'}
    return render(request,'ttsx_user/register.html',context)


#获取用户注册信息,将用户信息存入数据库,并对密码进行shal1加密,
#并跳转到登录界面
def register_handle(request):
    #获取输入的值
    p = request.POST
    uname = p.get('user_name')
    upwd = p.get('user_pwd')
    umail = p.get('user_email')
    #对密码进行加密
    s1 = sha1()
    s1.update(upwd)
    upwd_sha1 = s1.hexdigest()

    #获取对象,保存到数据库
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd_sha1
    user.umail = umail
    user.save()
    return redirect('/user/login/')


#在注册时判断用户是否已经注册
def register_estimate(request):
    uname = request.GET.get('uname')
    result = UserInfo.objects.filter(uname=uname).count()
    context = {'valid':result}
    return JsonResponse(context)


#跳转到登录界面
def login(request):
    uname = request.COOKIES.get('uname', '')
    context = {'title':'登录','uname':uname,'top':'0'}
    return render(request,'ttsx_user/login.html',context)


def login_handle(request):
    #得到用户输的用户名和密码
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('user_pwd')
    uname_jz = post.get('name_jz','0')
    #对用户输入的用户名进行加密
    s1 = sha1()
    s1.update(upwd)
    upwd_sha1 = s1.hexdigest()

    #如果用户名错误,提交以后将显示在页面上
    context = {'title':'登录','uname':uname,'upwd':upwd,'top':'0'}
    #如果用户名存在,返回users=[<UserInfo: python>],不存在的话[]一个空的列表
    users = UserInfo.objects.filter(uname=uname)
    # print users
    # print users[0]
    if len(users) == 0:
        #表示用户名不存在
        context['name_error'] = '1'
        return render(request,'ttsx_user/login.html',context)
    else:
        if users[0].upwd == upwd_sha1:
            #记住登录用户
            request.session['uname'] = users[0].uname
            request.session['uid'] = users[0].id
            #记住用户名
            path=request.session.get('url_path','/')
            response=redirect(path)
            if uname_jz == '1':
                response.set_cookie('uname', uname, expires=datetime.datetime.now() + datetime.timedelta(days=7))
            #不想记住用户名
            else:
                response.set_cookie('uname','',max_age=-1)
            return response
        else:
            context['pwd_error'] = '1'
            return render(request,'ttsx_user/login.html',context)


# 判断用户是否登录,用于购物车
def islogin(request):
    result = 0
    if request.session.has_key('uid'):
        result = 1
    return JsonResponse({'islogin':result})


#清除路径
def logout(request):
    request.session.flush()
    return redirect('/user/login/')

#定义一个装饰器
def zhuang(func):
    def log(request,*args,**kwargs):
        # 判断用户是否登录
        if request.session.has_key('uid'):
            # 如果登录，则继续执行视图
            return func(request,*args,**kwargs)
        else:
            # 如果没登录，则转到登录页
            return redirect('/user/login/')
    return log

#center = zhuang(center)
@zhuang
#用户中心
def center(request):
    user = UserInfo.objects.get(pk=request.session['uid'])
    #查询最近浏览
    gids = request.COOKIES.get('goods_ids', '').split(',')
    #因为刚开始有一个'',先要将其删除掉
    gids.pop()
    glist = []
    for gid in gids:
        glist.append(GoodsInfo.objects.get(id=gid))
    context = {'title':'用户中心','user':user,'list':glist}
    return render(request,'ttsx_user/center.html',context)

@zhuang
#订单
def order(request):
    pindex = int(request.GET.get('pindex','1'))
    # 查询当前用户所有订单,并进行分页
    uid = request.session.get('uid')
    order_list = OrderMain.objects.filter(user_id=uid).order_by('-order_date')
    p = Paginator(order_list,1)
    order_page = p.page(pindex)
    page_list = []
    if p.num_pages<5:
        page_list = p.page_range
    elif order_page.number <=2:
        page_list = range(1,6)
    elif order_page.number >= p.num_pages-1:
        page_list = range(p.num_pages-4,p.num_pages+1)
    else:
        page_list = range(pindex-2,pindex+3)
    context = {'title':'用户订单','order_page':order_page,'page_list':page_list}
    return render(request,'ttsx_user/order.html',context)

@zhuang
#收货地址
def site(request):
    user = UserInfo.objects.get(pk=request.session['uid'])
    if request.method == 'POST':
        #获取输入的内容
        post = request.POST
        ushou = post.get('ushou')
        uphone = post.get('uphone')
        uaddress = post.get('uaddress')

        #将输入的内容保存到数据库
        user.ushou = ushou
        user.uphone = uphone
        user.uaddress = uaddress
        user.save()

    context = {'title': '收货地址','user':user}
    return render(request, 'ttsx_user/site.html', context)

ttsx/templates/ttsx_user/center.html
{%extends 'base.html'%}
{%block qu1%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/center/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user.uname}}</li>
							<li><span >电子邮箱:</span>{{user.umail}}</li>
							<!--<li><span>联系地址：</span>北京市昌平区</li>-->
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
					{%for goods in list%}
					<li>
						<a href="/{{goods.id}}/"><img src="/static/{{goods.gpic}}"></a>
						<h4><a href="/{{goods.id}}/">{{goods.gtitle}}</a></h4>
						<div class="operate">
							<span class="prize">￥{{goods.gprice}}</span>
							<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
							<a href="#" class="add_goods" title="加入购物车"></a>
						</div>
					</li>
					{%endfor%}
					</ul>
				</div>
		</div>
	</div>
{%endblock qu1%}



ttsx/templates/ttsx_user/login.html
{%extends 'base.html'%}

{%block head%}
<script>
	name_ok = true;
	pwd_ok = true;
	$(function () {
		$('.name_input').blur(function() {
		    uname = $(this).val();
			len = uname.length;
			if(len<5||len>20)
			{
				$('.user_error').html('请输入5-20个字符的用户名').show();
				name_ok = false;
			}
			else{
		        $('.user_error').hide();
				name_ok = true;
            }
        });
		$('.pass_input').blur(function () {
			upwd = $(this).val();
			len = upwd.length;
			if(len<8||len>20){
			$('.pwd_error').html('密码最少8位，最长20位').show();
			pwd_ok = false;
			}
		else
		{
			$('.pass_input').next().hide();
			pwd_ok= true;
		}

        });
		$('form').submit(function () {
			$('.name_input').blur();
			$('.pass_input').blur();
			return name_ok && pwd_ok;
        });
		if('{{name_error}}'=='1'){
				$('.user_error').html('用户名错误').show();
				name_ok =false;
		}
		if('{{pwd_error}}' == '1'){
			$('.pwd_error').html('密码错误').show();
			pwd_ok = false;
		}
    })
</script>
{%endblock head%}

{%block qu1%}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="/user/login_handle/">
						{%csrf_token%}
						<input type="text" name="user_name"  value="{{uname}}" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="user_pwd" value="{{upwd}}" class="pass_input" placeholder="请输入密码" >
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="name_jz" value="1" >
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{%endblock qu1%}

ttsx/templates/ttsx_user/order.html
{%extends 'base.html'%}

{%block head%}
<script>
	$(function () {
		$('.col04').each(function () {
			count = parseInt($(this).prev().text());
			price = parseFloat($(this).prev().prev().find('span').text());
			$(this).text((count*price).toFixed(2)+'元');
        })
    })
</script>
{%endblock head%}

{%block qu1%}
<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="/user/center/">· 个人信息</a></li>
			<li><a href="/user/order/" class="active">· 全部订单</a></li>
			<li><a href="/user/site/">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
		{%for order in order_page%}
			<h3 class="common_title2">全部订单</h3>
			<ul class="order_list_th w978 clearfix">
				<li class="col01">{{order.order_date}}</li>
				<li class="col02">订单号:{{order.order_id}}</li>
				<li class="col02 stress">{%if order.state == 1%}已支付{%else%}未支付{%endif%}</li>
			</ul>

			<table class="order_list_table w980">
				<tbody>
					<tr>
						<td width="55%">
						{%for detail in order.orderdetail_set.all%}
							<ul class="order_goods_list clearfix">
								<li class="col01"><img src="/static/{{detail.goods.gpic}}"></li>
								<li class="col02">{{detail.goods.gtitle}}<em><span>{{detail.goods.gprice}}</span>元/{{detail.goods.gunit}}</em></li>
								<li class="col03">{{detail.count}}</li>
								<li class="col04">0</li>
							</ul>
						{%endfor%}
						</td>
						<td width="15%">{{order.total}}元</td>
						{%if detail.state == 1%}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						{%else%}
							<td width="15%">去付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						{%endif%}
					</tr>
				</tbody>
			</table>
		{%endfor%}
			<div class="pagenation">
			{%if order_page.has_previous%}
				<a href="?pindex=1">首页</a>
				<a href="?pindex={{order_page.number|add:-1}}">上一页</a>
			{%endif%}

			{%for pindex in page_list%}
				{%if pindex == order_page.number%}
					<a href="#" class="active">{{pindex}}</a>
				{%else%}
					<a href="?pindex={{pindex}}">{{pindex}}</a>
				{%endif%}
			{%endfor%}

				{%if order_page.has_next%}
					<a href="?pindex={{order_page.number|add:1}}">下一页</a>
					<a href="?pindex={{order_page.paginator.num_pages}}">末页</a>
				{%endif%}
			</div>
	</div>
</div>
{%endblock qu1%}



ttsx/templates/ttsx_user/register.html
{%extends 'base.html'%}

	{%block head%}
	<script type="text/javascript" src="/static/js/register.js"></script>
	{%endblock head%}

{%block qu1%}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/user/register_handle/" id="reg_form" >
					{%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="user_pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="user_email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{%endblock qu1%}

ttsx/templates/ttsx_user/site.html
{%extends 'base.html'%}
{%block qu1%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/center/">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{user.uaddress}} （{{user.ushou}} 收） 联系方式:{{user.uphone}} {{user.ucode}}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="/user/site/">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="ucode">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" >
						</div>

						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{%endblock qu1%}

